#!/usr/bin/env python
"""polo

CLI and library to trade on the Poloniex exchange by its RESTful API
https://poloniex.com

Copyright (c) 2016, 2018 Alvaro Figueiredo
alvaro.af@gmail.com

On Python 3:
pip install requests

On Python 2:
pip install requests
pip install future
"""


from __future__ import unicode_literals, print_function
from builtins import str


try:
    # Python 2
    from urllib import urlencode
except ImportError:
    # Python 3
    import urllib3
    from urllib.parse import urlencode


import json
import hashlib
import hmac
import sys
import time
import requests


_APIURL = 'https://poloniex.com/tradingApi'
_LENDINGRATE = 0.004
HELP = '''\
Examples:

polo balance
polo summary                  # margin
polo tradable                 # margin
polo position BTC_ETH         # margin
polo long BTC_ETH 0.01981 10  # margin
polo short BTC_ETH 0.01981 10 # margin
polo close BTC_ETH            # margin
polo buy BTC_ETH 0.01981 10   # exchange
polo sell BTC_ETH 0.01981 10  # exchange
polo orders BTC_ETH
polo trades 40829005273
polo cancel 40829005273
polo move 40829005273 0.01981 [10]
polo transfer ETH 10 exchange margin
'''


def nonce(factor=3000000000):
    """Evaluate the next nonce"""
    return int(factor * time.time())


class RequestData(dict):
    """Assemble the data to make a request to the API"""

    commands = {
        'b0': 'returnBalances',
        'b1': 'returnCompleteBalances',
        'balance': '_assemble_balance',
        'summary': '_assemble_summary',
        'position': '_assemble_position',
        'buy': '_assemble_buy',
        'long': '_assemble_long',
        'sell': '_assemble_sell',
        'short': '_assemble_short',
        'move': '_assemble_move',
        'orders': '_assemble_orders',
        'cancel': '_assemble_cancel',
        'trades': '_assemble_trades',
        'tradable': '_assemble_tradable',
        'transfer': '_assemble_transfer',
        'close': '_assemble_close',
    }

    def __init__(self, args, nonce_=None):
        super(RequestData, self).__init__()
        if isinstance(args, str):
            args = args.split()
        self.args = args
        super(RequestData, self).__setitem__(
            'nonce', nonce_ if nonce_ is not None else nonce()
        )
        #super(RequestData, self).__setitem__('account', 'margin')
        getattr(self, RequestData.commands[self.args[1]])()

    @staticmethod
    def _currency_pair(args):
        # Parse the currency pair from args
        if 2 < len(args):
            curr_pair = args[2]
            if curr_pair != 'all':
                curr_pair = curr_pair.upper()
                if '_' not in curr_pair:
                    curr_pair = 'BTC_' + curr_pair
        else:
            curr_pair = 'all'
        return curr_pair

    def _assemble_balance(self):
        super(RequestData, self).__setitem__(
            'command', 'returnAvailableAccountBalances'
        )
        super(RequestData, self).__setitem__('account', 'all')

    def _assemble_summary(self):
        super(RequestData, self).__setitem__(
            'command', 'returnMarginAccountSummary'
        )

    def _assemble_position(self):
        super(RequestData, self).__setitem__('command', 'getMarginPosition')
        super(RequestData, self).__setitem__(
            'currencyPair', self._currency_pair(self.args)
        )

    def _assemble_buy(self):
        super(RequestData, self).__setitem__('command', 'buy')
        super(RequestData, self).__setitem__(
            'currencyPair', self._currency_pair(self.args)
        )
        super(RequestData, self).__setitem__('rate', float(self.args[3]))
        super(RequestData, self).__setitem__('amount', float(self.args[4]))

    def _assemble_long(self):
        super(RequestData, self).__setitem__('command', 'marginBuy')
        super(RequestData, self).__setitem__(
            'currencyPair', self._currency_pair(self.args)
        )
        super(RequestData, self).__setitem__('rate', float(self.args[3]))
        super(RequestData, self).__setitem__('amount', float(self.args[4]))
        super(RequestData, self).__setitem__('lendingRate', _LENDINGRATE)

    def _assemble_sell(self):
        super(RequestData, self).__setitem__('command', 'sell')
        super(RequestData, self).__setitem__(
            'currencyPair', self._currency_pair(self.args)
        )
        super(RequestData, self).__setitem__('rate', float(self.args[3]))
        super(RequestData, self).__setitem__('amount', float(self.args[4]))

    def _assemble_short(self):
        super(RequestData, self).__setitem__('command', 'marginSell')
        super(RequestData, self).__setitem__(
            'currencyPair', self._currency_pair(self.args)
        )
        super(RequestData, self).__setitem__('rate', float(self.args[3]))
        super(RequestData, self).__setitem__('amount', float(self.args[4]))
        super(RequestData, self).__setitem__('lendingRate', _LENDINGRATE)

    def _assemble_move(self):
        super(RequestData, self).__setitem__('command', 'moveOrder')
        super(RequestData, self).__setitem__('orderNumber', self.args[2])
        super(RequestData, self).__setitem__('rate', float(self.args[3]))
        if 4 < len(self.args):
            super(RequestData, self).__setitem__('amount', float(self.args[4]))

    def _assemble_orders(self):
        super(RequestData, self).__setitem__('command', 'returnOpenOrders')
        super(RequestData, self).__setitem__(
            'currencyPair', self._currency_pair(self.args)
        )

    def _assemble_cancel(self):
        super(RequestData, self).__setitem__('command', 'cancelOrder')
        super(RequestData, self).__setitem__('orderNumber', self.args[2])

    def _assemble_trades(self):
        super(RequestData, self).__setitem__('command', 'returnOrderTrades')
        super(RequestData, self).__setitem__('orderNumber', self.args[2])

    def _assemble_tradable(self):
        super(RequestData, self).__setitem__(
            'command', 'returnTradableBalances'
        )

    def _assemble_transfer(self):
        super(RequestData, self).__setitem__('command', 'transferBalance')
        super(RequestData, self).__setitem__('currency', self.args[2].upper)
        super(RequestData, self).__setitem__('amount', float(self.args[3]))
        super(RequestData, self).__setitem__('fromAccount', self.args[4])
        super(RequestData, self).__setitem__('toAccount', self.args[5])

    def _assemble_close(self):
        super(RequestData, self).__setitem__('command', 'closeMarginPosition')
        super(RequestData, self).__setitem__(
            'currencyPair', self._currency_pair(self.args)
        )


def encode(data):
    """Encode the data dictionary"""
    return urlencode(data).encode('utf-8')


def sign(secret, coding):
    """Digitally sign the coding using the API Secret"""
    return hmac.new(secret, coding, hashlib.sha512).hexdigest()


def request(apikey, sign_, data, proxy=None):
    """Make a request to the API"""
    headers = {'Key': apikey, 'Sign': sign_}
    resp = requests.post(_APIURL, headers=headers, proxies=proxy, data=data)
    return json.loads(resp.text)


def main(args):
    """Drive the execution if it is called as a program"""
    import settings
    if args[1] == 'help':
        print(HELP, end='')
        return
    nonce_ = nonce(settings.NonceFactor)
    data = RequestData(args, nonce_)
    coding = encode(data)
    sign_ = sign(settings.Secret, coding)
    response = request(settings.ApiKey, sign_, data, settings.Proxy)
    print(
        json.dumps(
            response, sort_keys=True,
            separators=(',', ': '), indent=2
        )
    )


if __name__ == '__main__':
    main(sys.argv)
